### ISSUE TITLE
Error: auth_time in id_token does not match original auth_time

### ISSUE THREAD

**Issue by phlegx** [authts/oidc-client-ts#1111]
Hi!

I get this error after `signinSilent`. The `auth_time` sames ok. Any idea why this error is thrown?

`Error: auth_time in id_token does not match original auth_time`

Best regards

**Comment by pamapa** [comment]
`auth_time` from the spec:
Time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. When a max_age request is made or when auth_time is requested as an Essential Claim, then this Claim is REQUIRED; otherwise, its inclusion is OPTIONAL. (The auth_time Claim semantically corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] auth_time response parameter.)

**Comment by apliez** [comment]
Hi, 

I have the exact same problem, do you have a solution to solve it ?
I see that auth.user.profile.auth_time is undefined in my case but I don't know if this is linked to this error.

Best regards,

**Comment by pamapa** [comment]
Which version are you using `auth_time` has been some time ago. See https://github.com/authts/oidc-client-ts/releases/tag/v2.2.4

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
