### ISSUE TITLE
UserManager signoutRedirect not working

### ISSUE THREAD

**Issue by ch-lepp** [authts/oidc-client-ts#1379]
To logout I use the[ signoutRedirect method of the UserManager](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signoutRedirect).
That worked perfectly fine with version 2.4.0.

With version 3.0.0 the user is no longer properly logged out.

oidc-client-ts correctly redirects the user agent to the auth server with id_token_hint and post_logout_redirect_uri.
The auth server performs the logout as usual and redirects the user agent back to the application.

The difference compared to version 2.4.0 is, that the UserManager still holds a user object, accesible by the [getUser method](https://authts.github.io/oidc-client-ts/classes/UserManager.html#getUser).

Causing the issue should be the removal of [this line in the _signoutStart method](https://github.com/authts/oidc-client-ts/blob/v2.4.0/src/UserManager.ts#L552).

Is this a bug or should I change some things in my application?

**Comment by ch-lepp** [comment]
The [migration guide](https://github.com/authts/oidc-client-ts/blob/main/docs/migration.md) is not mentioning this at all btw.
It probably should...

**Comment by pamapa** [comment]
Can you verify if that is caused by https://github.com/authts/oidc-client-ts/pull/1342?

**Comment by ch-lepp** [comment]
Yes, reverting the mentioned PR solves my issue.

I think the underlying problem is the following:

I have not implemented the logout callback functionality in my application.
I do have a dedicated endpoint for login and refresh callbacks, because here the application actually has stuff to do (e.g. changing an auth code for an access token).
But after a logout I assumed no special actions need to be taken and therefor I simply redirect to the applications main page.

So the signoutRedirectCallback method as well as the _signoutEnd method never get called...

**Comment by ch-lepp** [comment]
I have to add, that I originally come from the oidc-client-js lib.
Here the [signoutCallback was merely a logger](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/UserManager.js#L536C21-L536C43).

So there was actually no real reason to use it.

Same goes for the oidc-client-ts library since the last major update.
In Version 2.4.0 the [signoutCallback seems to have a simple logging purpose](https://github.com/authts/oidc-client-ts/blob/v2.4.0/src/UserManager.ts#L570)...

**Comment by pamapa** [comment]
I see multiple solutions:
1. reverting #1342
  - PRO: simple
  - NEG: raise condition of events, but we had them since ever 
2. when `_signoutStart` and `_signoutEnd` are called in sequence (without callback) we defer the `removeUser` else keep as before #1342
  - PRO: probably keeps the event raise condition fixed and does not depend if callback is not called. To be checked first.
  - NEG: remove user if called differently, once in `_signoutStart` else in `_signoutEnd`
3. keep as we have it
  - PRO: simple
  - NEG: if no callback or for whatever reason the call back is not called, the user remains  and not event is raised

Any other solutions?

@PSanetra Would version 2. work for you? 

I am thinking about reverting, because its dead simple and makes sure that the user is removed and the event is sent at any situation. Maybe version 2. would be a compromise. I no longer like version 3. though...

**Comment by PSanetra** [comment]
@pamapa Please do not revert that PR.

I am not sure what the issue is. Is there a case where _signoutEnd is never called? This seems to be generally wrong :confused: 

Is the client not required to call _signoutEnd somehow?

Even if there are existing clients which do not call `UserManager.signoutCallback` or `UserManager.signoutRedirectCallback`: Is it not better to fix the clients which miss this callback? Otherwise it is probably better to remove this callback handler completely?!

I would be ok to introduce a flag to the UserManager to configure if such a callback is supported by the client or not. If it is supported, the behavior, introduced by the PR should be maintained, otherwise I would be fine to fall back to the pre-PR behavior, which is prone to race conditions.

**Comment by pamapa** [comment]
@ch-lepp I guess you can easily implement that callback, `_signoutEnd` must really be called otherwise we have too many different code paths, thus makes everything more easy. We can adapt the migration notice for others...

**Comment by ch-lepp** [comment]
Yes, I could use the callback.
That indeed fixes the issue for me.

Thank you for your support.

**Comment by pamapa** [comment]
i have improved the migration document

**Comment by pamapa** [comment]
i am not so sure if the callback is called by all IDPs....

**Comment by PSanetra** [comment]
@pamapa I think defering the notification would also be ok. Our original issue was only caused by a race condition between that event notification handling and the actual logout. As far as I know our application does not directly depend on that internal persistent state.

Regarding the local storage state: I did not look deep into the reason why this state is necessary. Might it be possible to completely remove this persistent state? Usually the login flow will anyway work also without such a state, right? Maybe I am missing something, but I think it might be possible to remove the persistent state.

**Comment by pamapa** [comment]
> I think defering the notification would also be ok. Our original issue was only caused by a race condition between that event notification handling and the actual logout. As far as I know our application does not directly depend on that internal persistent state.

So tricky, what if we only defer the notify: user is removed (good), but rest of application is not notified -> not good.


>Regarding the local storage state:
Can you move that into a new issue, it is better to track it separately...

**Comment by pamapa** [comment]
I do not want to enforce the users of this library to implement a callback by default. I am going to revert to the previous 100% reliable behavior.

**Comment by WtfJoke** [comment]
Thanks for the fast release :) I was searching for an issue over at https://github.com/authts/react-oidc-context
