### ISSUE TITLE
Revoking access token fails

### ISSUE THREAD

**Issue by Frozenlock** [authts/oidc-client-ts#262]
Migrating from [oidc-client-js](https://github.com/IdentityModel/oidc-client-js/).
In `oidc-client-ts` revoking no longer works.

It is my understanding that when revoking an access token, it's the **refresh token** that should be sent to the revoke endpoint.
See the Cognito documentation:

> The refresh token that the client wants to revoke. All access tokens issued from this refresh token are also revoked.

https://docs.aws.amazon.com/cognito/latest/developerguide/revocation-endpoint.html

`oidc-client-ts` (wrongly?) sends the access token, which results in the following error:
> HTTP 400 and error unsupported_token_type is returned if the token sent in the revocation request is not a refresh token

**Comment by kherock** [comment]
The protocol allows revoking both kinds of tokens, spec [here](https://datatracker.ietf.org/doc/html/rfc7009#section-2.1). 

It looks like the old implementation attempted to revoke both the access and refresh tokens and then returned success if at least one of them succeeded.

https://github.com/IdentityModel/oidc-client-js/blob/d700897e0a9e5eac060b12a687d55606535ca5e9/src/UserManager.js#L565-L584

This behavior feels a bit strange since the revocation endpoint is highly implementation dependent. The 400 you're seeing is likely the result of sending `token_type_hint=access_token` to Cognito's endpoint.

I think the settings for this could be improved so that you have more control over the success of a revocation request. @pamapa do the following updates to the revocation APIs seem reasonable?

* `UserManagerSettings.revokeAccessTokenOnSignout: boolean`
  * rename to `UserManagerSettings.revokeTokensOnSignout: ('access_token' | 'id_token')[]`
  * configures a list of token types to revoke upon sign out
* `UserManager.revokeAccessToken()`
  * rename to `UserManager.revokeToken(typeHint: 'access_token' | 'id_token')`
  * rather than attempting to revoke both types, only revokes the type specified

**Comment by pamapa** [comment]
@kherock makes sense, default should be revoke all types like before

**Comment by kherock** [comment]
Ignore the `'id_token'` string, I meant `'refresh_token'`, sorry!

I'm a bit uncomfortable having `revokeToken` take the entire list of types since it makes the errors harder to deal with. Without additional context in the thrown error object, the caller won't be able to tell which revocation failed. Though I think this should be possible to alleviate by extending `ErrorResponse` with a `.request` property containing the form body.

**Comment by pamapa** [comment]
> I'm a bit uncomfortable having `revokeToken` take the entire list

Alternate solution would be do **not** add the new argument to the public function `UserManager.revokeToken`. We only add the settings part. Its less flexible, but what would be the use case to only revoke something and not all possible?
