### ISSUE TITLE
signinSilent Iframe should notify parent on error

### ISSUE THREAD

**Issue by Frozenlock** [authts/oidc-client-ts#366]
If the Iframe throws an error before loading the silent redirect URL, nothing is sent to the parent window and we need to wait for the timeout.

Why is it a problem?

In our case we try `signinSilent` as the first method for signin in. Only if it fails does the user need to manually enter his credentials. As the failure is expected, there should be a way to quickly notify the parent window.

**Comment by pamapa** [comment]
Why is the timeout not good enough? Please provide more context: your settings + oidc console log (enable via `Log.setLogger(console); Log.setLevel(Log.INFO);`

**Comment by kherock** [comment]
I think I need more details about the nature of the error here. Normally, the parent __is__ immediately notified when a `prompt=none` authorization fails, assuming you've appropriately implemented your callback endpoint. If the authorization request fails due to some iframe policy or an improper `prompt=none` implementation, there's not much we can do beyond waiting for a timeout to expire. In those cases, the iframe is stuck on a foreign origin where we can't communicate with it.

**Comment by Frozenlock** [comment]
The Iframe is first sent to `/oauth2/authorize`.

If the user is logged in, then the browser is redirected to our configured `silent_redirect_uri` and everything is fine.

If the user isn't logged in however, then the response is a 302 redirecting to the login page, which cannot be displayed. (both because the `x-frame-options` is set to `deny` and because the Iframe is hidden.)

When I opened this ticket I thought we could simply listen for the display error, but while it appears in Chrome's console, on a closer look it might not even be a catchable/listenable error:

![image](https://user-images.githubusercontent.com/1152041/153044890-113224c6-b940-456e-9f77-9172c242cf44.png)

So at this point I don't really know how to tackle this problem. Is it even possible?

> Why is the timeout not good enough?

Because we either put a short timeout and let those with a slow connection suffer, or we put a long timeout and now everyone who isn't logged in must wait before being redirected to the login page.

**Comment by kherock** [comment]
You need to adjust your `X-Frame-Options`. The page served by your `silent_redirect_uri` should allow being displayed in an iframe and should call the silent callback, example here:

https://github.com/authts/oidc-client-ts/blob/main/samples/Parcel/src/user-manager/sample-silent.js

**Comment by Frozenlock** [comment]
Alas, like I said above, my page is fine.

My OIDC provider automatically redirects to a login page if the user isn't logged in.
I was hoping `oidc-client-ts` could do something with the "Refused to display" error.

**Comment by kherock** [comment]
I don't think there's anything we can do since we can't communicate with the iframe while a foreign origin is loaded. Your OIDC provider isn't up to spec:

> prompt
OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. The defined values are:
none
The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in [Section 3.1.2.6](https://openid.net/specs/openid-connect-core-1_0.html#AuthError). This can be used as a method to check for existing authentication and/or consent.

**Comment by Frozenlock** [comment]
Now that I know what I'm looking for, it does indeed look like my OIDC provider (Cognito) is the culprit.
Apparently it's been an issue for **years**.

https://github.com/aws-amplify/amplify-js/issues/1218#issuecomment-799022514

Thank you very much for your detailed explanation, and my apologies for having wasted your time with an issue that wasn't even caused by `oidc-client-ts`.
