### ISSUE TITLE
Error Authenticating to Okta. Origin header must not be included in token request

### ISSUE THREAD

**Issue by dberry-rcs** [authts/oidc-client-ts#395]
Okta reports an error that the request to retrieve the token contains the "Origin" header.  Is it possible to get an oidc setting that will remove the origin header?

The error message is: " Browser requests to the token endpoint must use Proof Key for Code Exchange."

The help page is here:

https://support.okta.com/help/s/article/Browser-requests-to-the-token-endpoint-must-use-Proof-Key-for-Code-Exchange?language=en_US

request information:

Request URL: https://*********.okta.com/oauth2/default/v1/token
Request Method: POST
Status Code: 401 
Remote Address: 3.15.36.193:443
Referrer Policy: strict-origin-when-cross-origin

**Request Headers**
:authority:***********.okta.com
:method: POST
:path: /oauth2/default/v1/token
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 337
content-type: application/x-www-form-urlencoded
**origin: http://localhost:3000**
referer: http://localhost:3000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Microsoft Edge";v="98"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.55

**RequestBody**
grant_type: authorization_code
redirect_uri: http://localhost:3000/login/callback
code: **************************************
code_verifier: *******************************************
client_id: ************************
client_secret: ************************

**Comment by dberry-rcs** [comment]
This issue does not make sense. I must be doing something wrong. This is client side so the browser always adds Origin. The PKCE is not working correctly so is probably something on my side. Any help would be appreciated.

**Comment by brockallen** [comment]
I"m not sure it's you. I don't understand the article myself. PKCE and browser-based clients are orthogonal (yet not incompatible) concepts. If you happen to make token endpoint request calls cross-origin, the Origin header would be included (as per the same-site policy and allowing CORS to override), and that's fine. And if you're not making the token request from a browser then the Origin header would not be present. It's a vary bizarre article.

**Comment by brockallen** [comment]
I asked: https://twitter.com/BrockLAllen/status/1497041937983057929

**Comment by aaronpk** [comment]
I'm looking into this, give me a few minutes to try something...

**Comment by aaronpk** [comment]
Alright, there are two things going on here. The error message is misleading, but it is correctly rejecting this request.

I see you have a `client_secret` in that request. That means you created the app as a "Web App" in Okta, rather than a "Single-Page App". Okta won't give a client secret to an app that you've registered as a Single-Page App.

What's happening is Okta is rejecting the request because you shouldn't be using a client secret from a browser since a single-page app is a public client, and can't keep the secret confidential.

If you register the app as a Single-Page App in Okta and configure this client with only the client_id and no secret, it will work.

I was able to verify this just now by using my vanilla JS client both with and without a client secret, and I got the same error message you got when I included the secret. The error message is really bad in this case, but it's correctly trying to prevent this exact situation.

**Comment by dberry-rcs** [comment]
Thanks, you were right. I was using an existing application inside of Okta which was a web app and not a SPA. SPA is only apparent on creation, not readily apparent when looking at an existing application. I created the SPA application in Okta and it worked.
