### ISSUE TITLE
User expired property always true

### ISSUE THREAD

**Issue by cameronturner444** [authts/oidc-client-ts#458]
I recently ran into an issue where the user `expired` property was always true even just after receiving a new token from the identity server.

The current `User.test.ts` passes but if it is updated to use jest mock timers, it fails.

Example:

```
import { User } from "./User";

describe("User", () => {
    beforeEach(() => {
        jest.useFakeTimers(); // changed from jest.spyOn
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    describe("expired", () => {
        it("should calculate how much time left", () => {
            const subject = new User({ expires_at: 100 } as never);
            expect(subject.expired).toEqual(false);

            // act
            jest.advanceTimersByTime(100); // changed from "now += 100"

            // assert
            expect(subject.expired).toEqual(true);
        });
    });
```

**Comment by pamapa** [comment]
Please provide more information why it kept `expired`. Do not argue with unit-tests. `expired` is a calculated property, the base for the calculation is the `expires_at` property, which comes over the wire from the identity server. Please report the sequence of `expires_at` you received.

**Comment by cameronturner444** [comment]
the expired at property coming from identity server is `1800` which isn't too different from the unit test.

i was trying to point out that the current unit test doesn't really seem to reflect real world usage since `getEpochTime` doesn't ever seem to return 0 like is setup in the test.

**Comment by kherock** [comment]
@pamapa that code removed in the diff wasn't setting `expires_in`, it was a redundant assignment ensuring that `expires_in` is stored as a number as opposed to a string. I removed it since we already cast it as a number in the getter.

The actual assignment occurs in the `Object.assign` when the code is retrieved:
https://github.com/authts/oidc-client-ts/blob/8bf2b68629d9b48d79f28c8cfc88db2d5000d5b6/src/ResponseValidator.ts#L220-L228

The other one for refresh tokens is here:
https://github.com/authts/oidc-client-ts/blob/8bf2b68629d9b48d79f28c8cfc88db2d5000d5b6/src/OidcClient.ts#L176-L177

**Comment by pamapa** [comment]
@cameronturner444 `expires_in` can be 1800 (in seconds), but `expires_at` needs to be much higher, as it is the time in Unix epoch format and internally calculated...

**Comment by pamapa** [comment]
As changing the time (in unit-test) after the `expires_at` was calculated has no impact on the `expires_at`  i will soon close this issue, unless you report more info...
