### ISSUE TITLE
Is clockSkewInSeconds actually used?

### ISSUE THREAD

**Issue by justin-mellor** [authts/oidc-client-ts#552]
I may be missing something, but I can't see anywhere in the code where the value of clockSkewInSeconds is used. Does this mean that the JwtClaims are not being checked? Things like iat, nbf, exp. The same code in oidc-client also checked iss, aud and azp.

**Comment by pamapa** [comment]
`clockSkewInSeconds` was used to validate the id token for the implicit grant. We have drop the implicit grant in this library. For the PKCE flow we do not need to validate the token anymore, only decoding is done.

Thus that setting is a left over and must be removed.

**Comment by pamapa** [comment]
@Badisi can we drop that setting in a bugfix version or must we do a major one?

**Comment by Badisi** [comment]
I think the question was more directed to @kherock than me.

But anyhow, I would say a **major** one because even though that setting isn't use throughout the library, it is still publicly exposed through `OidcClientSettings` and as such removing it will cause a **breaking change** to any one that defined it.
