### ISSUE TITLE
signin popup doesn't close in safari on ios

### ISSUE THREAD

**Issue by tgass** [authts/oidc-client-ts#643]
Hello,

there seems to be a long history of non closing (signin) popups in Safari on ios. . So I noticed that the signin pop up of oidc-client-ts doesn't automatically close only on Safari on ios (15.6) and works just fine with ie Firefox. Even a very concrete `window.close()` or `setTimeout(window.close, 300)` in the signin-callback success handler doesn't work. Is this a common problem? I wonder, how do you handle this in your code? Is it an issue with my settings in safari? Is there something oidc-client-ts could do? Thank you for any feedback!

Best,
Tilmann

**Comment by dberardo-com** [comment]
have you tried with this callback: https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinPopupCallback ?

**Comment by tgass** [comment]
Thank you so much! Works!  ( . . somehow I didn't see that function . .sorry!)

**Comment by dberardo-com** [comment]
> Thank you so much! Works! ( . . somehow I didn't see that function . .sorry!)

nice to hear that @tgass.

i am myself struggling to implement a popup using the react implementation of this library. Do you happen to have used react in your code base as well? 

If so, could you share some hints on which attributes you passed to the `signinPopup()` function? because in my case it somehow starts an infinite popup-opening loop until it hits the browser limits and it works quite buggy therefore.
