### ISSUE TITLE
signinSilent failed after the browser reboot

### ISSUE THREAD

**Issue by Heromyth** [authts/oidc-client-ts#786]
I'm using oidc-client-ts 2.20 with Keycloak 19.0.1, and using `mgr.signinSilent` to refresh the access token.

After logged in with `mgr.signinRedirect`,  the `mgr.signinSilent` can refresh the access token successfully. 
Exit the APP totally after closing the browser, and open my APP again. The access/refresh token is loaded from the local store. However, they can be refreshed again with the `mgr.signinSilent`. Here is the error message:

```
ErrorResponse: login_required
    at ResponseValidator._processSigninState (http://10.1.23.200:5173/node_modules/.vite/deps/oidc-client-ts.js?v=2ac95190:1573:13)
    at ResponseValidator.validateSigninResponse (http://10.1.23.200:5173/node_modules/.vite/deps/oidc-client-ts.js?v=2ac95190:1500:10)
    at OidcClient.processSigninResponse (http://10.1.23.200:5173/node_modules/.vite/deps/oidc-client-ts.js?v=2ac95190:2006:27)
    at async UserManager._signinEnd (http://10.1.23.200:5173/node_modules/.vite/deps/oidc-client-ts.js?v=2ac95190:2974:28)
    at async UserManager._signin (http://10.1.23.200:5173/node_modules/.vite/deps/oidc-client-ts.js?v=2ac95190:2953:12)
    at async UserManager.signinSilent (http://10.1.23.200:5173/node_modules/.vite/deps/oidc-client-ts.js?v=2ac95190:2837:12)
    at async retriveRefreshToken (http://10.1.23.200:5173/src/services/auth-service.ts:19:20)
```

My question is how can I refresh the access token after reentering the APP totally. Should I interface with the Keycloak's API directly?

**Comment by alex-eliot** [comment]
You have to create a web store to store the data in.
```ts
import { UserManager, WebStorageStateStore } from "oidc-client-ts";

const userStore = new WebStorageStateStore({ store: localStorage });
```

And pass it in the `userStore` field while instantiating your UserManager

```ts
export const manager = new UserManager({
  authority: "<your_authority_url>",
  client_id: "<your_client_id>",
  redirect_uri: "<your_redirect_uri>",
  scope: "<your_scopes>",
  userStore: userStore,
});
```

**Comment by Moshyfawn** [comment]
Storing your token in local storage is a bad security advice

**Comment by alex-eliot** [comment]
> Storing your token in local storage is a bad security advice

OP asked for login persistence—we want to have a way to access refresh/access tokens after the browser session is closed (so a simple in-memory storage will not work). localStorage is a plug-and-play solution which is also secured under the Same Origin Policy. The only way it can be hijacked is by XSS attacks within the site (user-inputted data being not properly sanitized, malicious userscripts, malicious bookmark links).

The only thing that can offer you security against XSS attacks, all the while maintaining login persistence, is an HttpOnly cookie (which is by definition inaccessible by any JavaScript run on the client). However, this requires some backend setup (as in, you would provide the tokens provided to you via the OAuth redirect, and the backend would return a response that sets an HttpOnly cookie, or literally any method with which you are able to set an HttpOnly cookie with what you want).

Again, this is only to safeguard against XSS attacks, since this is pretty much the only client-side vulnerability to any storage utilizing the Same Origin Policy. Due to the complexity of implementing the HttpOnly cookie, and considering the only ways to 

This article goes into more detail: https://auth0.com/blog/secure-browser-storage-the-facts/
