### ISSUE TITLE
How to directly enter the user registration page from frontend client with UserManager

### ISSUE THREAD

**Issue by davidsx** [authts/oidc-client-ts#836]
The following allows frontend client to enter login page easily

`userManager.signinRedirect({ prompt: 'login', state: {} });`

Is there any way for user to sign up/register a new user directly?

**Comment by pamapa** [comment]
You mean automatic login? Yes that should doable by calling `userManager.signinRedirect` without user interaction...

**Comment by MetaMmodern** [comment]
@pamapa no, he means something simila to what keycloak-js provides. It has a `register()` method and when you call it the library redirects user straight to sign **UP** page, bypassing sign in page. To be clear, those 2 pages are on different routes in keycloak, so it's easy to do. I suppose it's not something oidc-way or universal and that's why it's not available in this library...
